version: 2
updates:
  # Check for updates to dependencies in package.json and pnpm-lock.yaml
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    reviewers:
      - "shikharx06"

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
