import { cn } from '../lib/utils';

/** Accept the public embed URL generated by Google Maps' Share dialog. */
export function googleMapEmbedUrl(value: string | null | undefined): string | null {
  if (!value) return null;
  try {
    const url = new URL(value);
    if (
      url.protocol !== 'https:' ||
      !['google.com', 'www.google.com'].includes(url.hostname) ||
      url.port ||
      url.username ||
      url.password ||
      url.pathname !== '/maps/embed' ||
      !url.searchParams.get('pb')?.startsWith('!')
    )
      return null;
    return url.toString();
  } catch {
    return null;
  }
}

export function GoogleMapEmbed({
  src,
  title,
  className,
}: {
  src: string | null | undefined;
  title: string;
  className?: string;
}) {
  const embedUrl = googleMapEmbedUrl(src);
  if (!embedUrl) return null;
  return (
    <iframe
      src={embedUrl}
      title={title}
      width="600"
      height="450"
      loading="lazy"
      allowFullScreen
      referrerPolicy="strict-origin-when-cross-origin"
      className={cn('block aspect-[4/3] h-auto w-full border-0', className)}
    />
  );
}
